# Generated by Django 5.0.6 on 2024-06-05 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destino',
            new_name='DestinosTuristicos',
        ),
        migrations.RenameField(
            model_name='destinosturisticos',
            old_name='destino',
            new_name='descripcionCiudad',
        ),
        migrations.RenameField(
            model_name='destinosturisticos',
            old_name='image',
            new_name='imagenCiudad',
        ),
        migrations.RenameField(
            model_name='destinosturisticos',
            old_name='nombre',
            new_name='nombreCiudad',
        ),
        migrations.RenameField(
            model_name='destinosturisticos',
            old_name='oferta',
            new_name='ofertaTour',
        ),
        migrations.RenameField(
            model_name='destinosturisticos',
            old_name='precio',
            new_name='precioTour',
        ),
    ]
