# Generated by Django 5.0.6 on 2024-06-12 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0003_alter_destinosturisticos_preciotour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('destinos', models.ManyToManyField(to='destinos.destinosturisticos')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinos.destinosturisticos')),
            ],
        ),
    ]
